/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'avis-recherche': AvisRecherche;
    people: Person;
    vehicles: Vehicle;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'avis-recherche': AvisRechercheSelect<false> | AvisRechercheSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'super-admin' | 'officer' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * 📁 Documents et fichiers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * 🔍 Véhicules recherchés
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avis-recherche".
 */
export interface AvisRecherche {
  id: string;
  vehicule: string;
  typeVehicule: string;
  numeroImmatriculation: string;
  numeroSerie?: string | null;
  marque: string;
  modele: string;
  couleur?: string | null;
  dateVol: string;
  ville: string;
  lieuVol: string;
  declarant: string;
  telephoneDeclarant: string;
  emailDeclarant?: string | null;
  circonstances?: string | null;
  agentEnregistrement?: (string | null) | User;
  statutRecherche: 'actif' | 'retrouve' | 'abandonne';
  dateRecuperation?: string | null;
  lieuRecuperation?: string | null;
  agentRecuperation?: (string | null) | User;
  circonstancesRecuperation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fichier des personnes et informations d'identification.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: string;
  /**
   * Photo d'identité de la personne
   */
  photo?: (string | null) | Media;
  prenom: string;
  nom: string;
  dateNaissance: string;
  lieuNaissance?: string | null;
  sexe?: ('M' | 'F' | 'X') | null;
  nationalite?: string | null;
  /**
   * Utilisé comme identifiant principal pour les recherches
   */
  numeroNational: string;
  numeroPasseport?: string | null;
  adresse?: string | null;
  telephone?: string | null;
  email?: string | null;
  /**
   * Cochez si la personne fait l'objet d'un avis de recherche
   */
  estArrete?: boolean | null;
  statut?: ('actif' | 'detenu' | 'recherche' | 'libere') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 🚗 Gestion complète du registre des véhicules
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: string;
  typeVehicule?: ('voiture' | 'moto' | 'tricycle' | 'camion' | 'engin_agricole' | 'autre') | null;
  statut?: ('actif' | 'vole' | 'retrouve') | null;
  numeroImmatriculation?: string | null;
  numeroSerie?: string | null;
  marque?: string | null;
  modele?: string | null;
  annee?: number | null;
  couleur?: string | null;
  numeroMoteur?: string | null;
  carburant?: ('essence' | 'diesel' | 'electrique' | 'hybride' | 'gpl' | 'autre') | null;
  /**
   * 🔧 Capacité du moteur
   */
  cylindree?: number | null;
  /**
   * ⚖️ Poids à vide
   */
  poids?: number | null;
  dateAchat?: string | null;
  paysOrigine?: string | null;
  /**
   * 💵 Montant total
   */
  prixAchat?: number | null;
  devise?: ('XOF' | 'EUR' | 'USD' | 'autre') | null;
  vendeur?: string | null;
  numeroFacture?: string | null;
  /**
   * 📊 Montant payé
   */
  droitsDouane?: number | null;
  taxes?: number | null;
  fraisImmatriculation?: number | null;
  /**
   * Facture, certificat douanier, etc.
   */
  documentImportation?: (string | null) | Media;
  typeProprietaire?: ('physique' | 'morale') | null;
  dateAcquisition?: string | null;
  nom?: string | null;
  ville?: string | null;
  numeroIdentite?: string | null;
  adresse?: string | null;
  telephone?: string | null;
  email?: string | null;
  /**
   * CNI, Passeport ou Registre du Commerce
   */
  documentProprietaire?: (string | null) | Media;
  /**
   * Changements de plaques et de propriétaires
   */
  historiqueChangements?:
    | {
        typeChangement?: ('plaque' | 'proprietaire' | 'les_deux') | null;
        dateChangement?: string | null;
        anciennePlaque?: string | null;
        nouvellePlaque?: string | null;
        ancienProprietaire?: string | null;
        nouveauProprietaire?: string | null;
        motif?: string | null;
        documentChangement?: (string | null) | Media;
        agentEnregistrement?: (string | null) | User;
        /**
         * Rempli automatiquement
         */
        officierSaisie?: (string | null) | User;
        /**
         * Rempli automatiquement
         */
        dateSaisie?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Infractions commises avec ce véhicule
   */
  infractions?:
    | {
        dateInfraction?: string | null;
        heureInfraction?: string | null;
        ville?: string | null;
        lieuInfraction?: string | null;
        typeInfraction?:
          | (
              | 'exces_vitesse'
              | 'stationnement'
              | 'sans_permis'
              | 'ivresse'
              | 'feu_rouge'
              | 'douane'
              | 'contrebande'
              | 'documents_falsifies'
              | 'autre'
            )
          | null;
        descriptionInfraction?: string | null;
        conducteur?: string | null;
        numeroPermis?: string | null;
        montantAmende?: number | null;
        amendePayee?: boolean | null;
        numeroPV?: string | null;
        agentVerbalisant?: (string | null) | User;
        documentInfraction?: (string | null) | Media;
        /**
         * Rempli automatiquement
         */
        officierSaisie?: (string | null) | User;
        /**
         * Rempli automatiquement
         */
        dateSaisie?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Détails du vol déclaré
   */
  informationsVol?: {
    dateVol?: string | null;
    heureVol?: string | null;
    ville?: string | null;
    lieuVol?: string | null;
    declarant?: string | null;
    telephoneDeclarant?: string | null;
    emailDeclarant?: string | null;
    circonstances?: string | null;
    numeroPlainte?: string | null;
    documentVol?: (string | null) | Media;
    /**
     * Rempli automatiquement
     */
    officierSaisie?: (string | null) | User;
    /**
     * Rempli automatiquement
     */
    dateSaisie?: string | null;
  };
  /**
   * Détails de la récupération du véhicule
   */
  informationsRecuperation?: {
    dateRecuperation?: string | null;
    heureRecuperation?: string | null;
    etatVehicule?: ('bon' | 'endommage' | 'tres_endommage') | null;
    lieuRecuperation?: string | null;
    recuperePar?: string | null;
    circonstancesRecuperation?: string | null;
    agentRecuperation?: (string | null) | User;
    documentRecuperation?: (string | null) | Media;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'avis-recherche';
        value: string | AvisRecherche;
      } | null)
    | ({
        relationTo: 'people';
        value: string | Person;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: string | Vehicle;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avis-recherche_select".
 */
export interface AvisRechercheSelect<T extends boolean = true> {
  vehicule?: T;
  typeVehicule?: T;
  numeroImmatriculation?: T;
  numeroSerie?: T;
  marque?: T;
  modele?: T;
  couleur?: T;
  dateVol?: T;
  ville?: T;
  lieuVol?: T;
  declarant?: T;
  telephoneDeclarant?: T;
  emailDeclarant?: T;
  circonstances?: T;
  agentEnregistrement?: T;
  statutRecherche?: T;
  dateRecuperation?: T;
  lieuRecuperation?: T;
  agentRecuperation?: T;
  circonstancesRecuperation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  photo?: T;
  prenom?: T;
  nom?: T;
  dateNaissance?: T;
  lieuNaissance?: T;
  sexe?: T;
  nationalite?: T;
  numeroNational?: T;
  numeroPasseport?: T;
  adresse?: T;
  telephone?: T;
  email?: T;
  estArrete?: T;
  statut?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  typeVehicule?: T;
  statut?: T;
  numeroImmatriculation?: T;
  numeroSerie?: T;
  marque?: T;
  modele?: T;
  annee?: T;
  couleur?: T;
  numeroMoteur?: T;
  carburant?: T;
  cylindree?: T;
  poids?: T;
  dateAchat?: T;
  paysOrigine?: T;
  prixAchat?: T;
  devise?: T;
  vendeur?: T;
  numeroFacture?: T;
  droitsDouane?: T;
  taxes?: T;
  fraisImmatriculation?: T;
  documentImportation?: T;
  typeProprietaire?: T;
  dateAcquisition?: T;
  nom?: T;
  ville?: T;
  numeroIdentite?: T;
  adresse?: T;
  telephone?: T;
  email?: T;
  documentProprietaire?: T;
  historiqueChangements?:
    | T
    | {
        typeChangement?: T;
        dateChangement?: T;
        anciennePlaque?: T;
        nouvellePlaque?: T;
        ancienProprietaire?: T;
        nouveauProprietaire?: T;
        motif?: T;
        documentChangement?: T;
        agentEnregistrement?: T;
        officierSaisie?: T;
        dateSaisie?: T;
        id?: T;
      };
  infractions?:
    | T
    | {
        dateInfraction?: T;
        heureInfraction?: T;
        ville?: T;
        lieuInfraction?: T;
        typeInfraction?: T;
        descriptionInfraction?: T;
        conducteur?: T;
        numeroPermis?: T;
        montantAmende?: T;
        amendePayee?: T;
        numeroPV?: T;
        agentVerbalisant?: T;
        documentInfraction?: T;
        officierSaisie?: T;
        dateSaisie?: T;
        id?: T;
      };
  informationsVol?:
    | T
    | {
        dateVol?: T;
        heureVol?: T;
        ville?: T;
        lieuVol?: T;
        declarant?: T;
        telephoneDeclarant?: T;
        emailDeclarant?: T;
        circonstances?: T;
        numeroPlainte?: T;
        documentVol?: T;
        officierSaisie?: T;
        dateSaisie?: T;
      };
  informationsRecuperation?:
    | T
    | {
        dateRecuperation?: T;
        heureRecuperation?: T;
        etatVehicule?: T;
        lieuRecuperation?: T;
        recuperePar?: T;
        circonstancesRecuperation?: T;
        agentRecuperation?: T;
        documentRecuperation?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}